update

diff --git a/helm/user-service-chart/values.yaml b/helm/user-service-chart/values.yaml
--- a/helm/user-service-chart/values.yaml
+++ b/helm/user-service-chart/values.yaml
@@ -161,7 +161,12 @@ job:
         - /bin/sh
         - -c
         - |
-          pg_restore -U postgres -h postgres-shopnow-postgresql.shopnow.svc.cluster.local -d postgres --no-owner --no-acl --if-exists $BACKUP_FILE_PATH;
+          if [ -f "$BACKUP_FILE_PATH" ]; then
+            pg_restore -U postgres -h postgres-shopnow-postgresql.shopnow.svc.cluster.local -d postgres --no-owner --no-acl --if-exists $BACKUP_FILE_PATH;
+          else
+            echo "Backup file not found at $BACKUP_FILE_PATH";
+            exit 1;
+          fi
       volumeMounts:
         - name: backup-volume
           mountPath: /backup
